#!/bin/sh
find \
    ./sdk/util/ ./sdk/core/ ./sdk/plugin/ ./plugins/ ./core/ ./mous-cli/ ./mous-qt/ ./mous-ncurses/ \
    -name "*.h" -o -name "*.hpp" -o -name "*.cpp" -o -name "*.cc" \
    | xargs wc | sort -k 4
